srs:
  # 直播服务器，带域名版和不带域名版
  server: https://localhost
  serverHost: http://localhost


  # 发起直播的秘钥
  publishSecret:
  # 发起直播的接口
  publishUri: /rtc/v1/whip/?app=live


  # srs登录的接口
  srsLogin: /terraform/v1/mgmt/login

  # srs登录的密码
  loginPassword:
  # 下面这两个需要token
  # 查询视频流的接口
  streamsUri: /api/v1/streams
  # 查询在线客户的接口，可以踢人，可以结束直播
  clientsUri: /api/v1/clients


  # 播放的url前缀
  playPrefix: https://localhost/live/