spring:
  datasource:
    username: root
    password: qwer123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.81.46:3306/bili?useUnicode=true&characterEncoding=utf-8
    hikari:
      connection-timeout: 1000